/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SurveyRouteImport } from './routes/survey'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DetectorRouteImport } from './routes/detector'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SurveyTopoRouteImport } from './routes/survey.topo'
import { Route as SurveyGprRouteImport } from './routes/survey.gpr'
import { Route as SurveyErtRouteImport } from './routes/survey.ert'
import { Route as ProjectsNewRouteImport } from './routes/projects.new'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as DetectorResultsRouteImport } from './routes/detector.results'
import { Route as DetectorHistoryRouteImport } from './routes/detector.history'
import { Route as SurveyTopoImportRouteImport } from './routes/survey.topo.import'
import { Route as SurveyTopoContourRouteImport } from './routes/survey.topo.contour'
import { Route as SurveyTopoExportRouteImport } from './routes/survey.topo.export'
import { Route as SurveyGprRadargramRouteImport } from './routes/survey.gpr.radargram'
import { Route as SurveyErtHeatmapRouteImport } from './routes/survey.ert.heatmap'
import { Route as SurveyErtAnomalyRouteImport } from './routes/survey.ert.anomaly'
import { Route as ProjectsProjectIdFilesFileIdRouteImport } from './routes/projects.$projectId.files.$fileId'
import { Route as DetectorHistoryScanIdRouteImport } from './routes/detector.history.$scanId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register', path: '/register', getParentRoute: () => rootRouteImport,
} as any)
const SurveyRoute = SurveyRouteImport.update({
  id: '/survey', path: '/survey', getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects', path: '/projects', getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding', path: '/onboarding', getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login', path: '/login', getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home', path: '/home', getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password', path: '/forgot-password', getParentRoute: () => rootRouteImport,
} as any)
const DetectorRoute = DetectorRouteImport.update({
  id: '/detector', path: '/detector', getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/', path: '/', getParentRoute: () => rootRouteImport,
} as any)
const SurveyTopoRoute = SurveyTopoRouteImport.update({
  id: '/topo', path: '/topo', getParentRoute: () => SurveyRoute,
} as any)
const SurveyGprRoute = SurveyGprRouteImport.update({
  id: '/gpr', path: '/gpr', getParentRoute: () => SurveyRoute,
} as any)
const SurveyErtRoute = SurveyErtRouteImport.update({
  id: '/ert', path: '/ert', getParentRoute: () => SurveyRoute,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/new', path: '/new', getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId', path: '/$projectId', getParentRoute: () => ProjectsRoute,
} as any)
const DetectorResultsRoute = DetectorResultsRouteImport.update({
  id: '/results', path: '/results', getParentRoute: () => DetectorRoute,
} as any)
const DetectorHistoryRoute = DetectorHistoryRouteImport.update({
  id: '/history', path: '/history', getParentRoute: () => DetectorRoute,
} as any)
const SurveyTopoImportRoute = SurveyTopoImportRouteImport.update({
  id: '/import', path: '/import', getParentRoute: () => SurveyTopoRoute,
} as any)
const SurveyTopoContourRoute = SurveyTopoContourRouteImport.update({
  id: '/contour', path: '/contour', getParentRoute: () => SurveyTopoRoute,
} as any)
const SurveyTopoExportRoute = SurveyTopoExportRouteImport.update({
  id: '/export', path: '/export', getParentRoute: () => SurveyTopoRoute,
} as any)
const SurveyGprRadargramRoute = SurveyGprRadargramRouteImport.update({
  id: '/radargram', path: '/radargram', getParentRoute: () => SurveyGprRoute,
} as any)
const SurveyErtHeatmapRoute = SurveyErtHeatmapRouteImport.update({
  id: '/heatmap', path: '/heatmap', getParentRoute: () => SurveyErtRoute,
} as any)
const SurveyErtAnomalyRoute = SurveyErtAnomalyRouteImport.update({
  id: '/anomaly', path: '/anomaly', getParentRoute: () => SurveyErtRoute,
} as any)
const ProjectsProjectIdFilesFileIdRoute = ProjectsProjectIdFilesFileIdRouteImport.update({
  id: '/files/$fileId', path: '/files/$fileId', getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const DetectorHistoryScanIdRoute = DetectorHistoryScanIdRouteImport.update({
  id: '/$scanId', path: '/$scanId', getParentRoute: () => DetectorHistoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/register': typeof RegisterRoute
  '/survey': typeof SurveyRouteWithChildren
  '/detector': typeof DetectorRouteWithChildren
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/survey/topo': typeof SurveyTopoRouteWithChildren
  '/survey/gpr': typeof SurveyGprRouteWithChildren
  '/survey/ert': typeof SurveyErtRouteWithChildren
  '/detector/results': typeof DetectorResultsRoute
  '/detector/history': typeof DetectorHistoryRouteWithChildren
  '/projects/$projectId/files/$fileId': typeof ProjectsProjectIdFilesFileIdRoute
  '/survey/topo/import': typeof SurveyTopoImportRoute
  '/survey/topo/contour': typeof SurveyTopoContourRoute
  '/survey/topo/export': typeof SurveyTopoExportRoute
  '/survey/gpr/radargram': typeof SurveyGprRadargramRoute
  '/survey/ert/heatmap': typeof SurveyErtHeatmapRoute
  '/survey/ert/anomaly': typeof SurveyErtAnomalyRoute
  '/detector/history/$scanId': typeof DetectorHistoryScanIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/register': typeof RegisterRoute
  '/survey': typeof SurveyRouteWithChildren
  '/detector': typeof DetectorRouteWithChildren
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/survey/topo': typeof SurveyTopoRouteWithChildren
  '/survey/gpr': typeof SurveyGprRouteWithChildren
  '/survey/ert': typeof SurveyErtRouteWithChildren
  '/detector/results': typeof DetectorResultsRoute
  '/detector/history': typeof DetectorHistoryRouteWithChildren
  '/projects/$projectId/files/$fileId': typeof ProjectsProjectIdFilesFileIdRoute
  '/survey/topo/import': typeof SurveyTopoImportRoute
  '/survey/topo/contour': typeof SurveyTopoContourRoute
  '/survey/topo/export': typeof SurveyTopoExportRoute
  '/survey/gpr/radargram': typeof SurveyGprRadargramRoute
  '/survey/ert/heatmap': typeof SurveyErtHeatmapRoute
  '/survey/ert/anomaly': typeof SurveyErtAnomalyRoute
  '/detector/history/$scanId': typeof DetectorHistoryScanIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/register': typeof RegisterRoute
  '/survey': typeof SurveyRouteWithChildren
  '/detector': typeof DetectorRouteWithChildren
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/survey/topo': typeof SurveyTopoRouteWithChildren
  '/survey/gpr': typeof SurveyGprRouteWithChildren
  '/survey/ert': typeof SurveyErtRouteWithChildren
  '/detector/results': typeof DetectorResultsRoute
  '/detector/history': typeof DetectorHistoryRouteWithChildren
  '/projects/$projectId/files/$fileId': typeof ProjectsProjectIdFilesFileIdRoute
  '/survey/topo/import': typeof SurveyTopoImportRoute
  '/survey/topo/contour': typeof SurveyTopoContourRoute
  '/survey/topo/export': typeof SurveyTopoExportRoute
  '/survey/gpr/radargram': typeof SurveyGprRadargramRoute
  '/survey/ert/heatmap': typeof SurveyErtHeatmapRoute
  '/survey/ert/anomaly': typeof SurveyErtAnomalyRoute
  '/detector/history/$scanId': typeof DetectorHistoryScanIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/' | '/forgot-password' | '/home' | '/login' | '/onboarding'
    | '/projects' | '/register' | '/survey' | '/detector'
    | '/projects/$projectId' | '/projects/new'
    | '/survey/topo' | '/survey/gpr' | '/survey/ert'
    | '/detector/results' | '/detector/history'
    | '/projects/$projectId/files/$fileId'
    | '/survey/topo/import' | '/survey/topo/contour' | '/survey/topo/export'
    | '/survey/gpr/radargram' | '/survey/ert/heatmap' | '/survey/ert/anomaly'
    | '/detector/history/$scanId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/' | '/forgot-password' | '/home' | '/login' | '/onboarding'
    | '/projects' | '/register' | '/survey' | '/detector'
    | '/projects/$projectId' | '/projects/new'
    | '/survey/topo' | '/survey/gpr' | '/survey/ert'
    | '/detector/results' | '/detector/history'
    | '/projects/$projectId/files/$fileId'
    | '/survey/topo/import' | '/survey/topo/contour' | '/survey/topo/export'
    | '/survey/gpr/radargram' | '/survey/ert/heatmap' | '/survey/ert/anomaly'
    | '/detector/history/$scanId'
  id:
    | '__root__' | '/' | '/forgot-password' | '/home' | '/login' | '/onboarding'
    | '/projects' | '/register' | '/survey' | '/detector'
    | '/projects/$projectId' | '/projects/new'
    | '/survey/topo' | '/survey/gpr' | '/survey/ert'
    | '/detector/results' | '/detector/history'
    | '/projects/$projectId/files/$fileId'
    | '/survey/topo/import' | '/survey/topo/contour' | '/survey/topo/export'
    | '/survey/gpr/radargram' | '/survey/ert/heatmap' | '/survey/ert/anomaly'
    | '/detector/history/$scanId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  SurveyRoute: typeof SurveyRouteWithChildren
  DetectorRoute: typeof DetectorRouteWithChildren
}

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdFilesFileIdRoute: typeof ProjectsProjectIdFilesFileIdRoute
}
const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdFilesFileIdRoute,
}
const ProjectsProjectIdRouteWithChildren = ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
  ProjectsNewRoute: typeof ProjectsNewRoute
}
const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
  ProjectsNewRoute,
}
const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(ProjectsRouteChildren)

interface SurveyTopoRouteChildren {
  SurveyTopoImportRoute: typeof SurveyTopoImportRoute
  SurveyTopoContourRoute: typeof SurveyTopoContourRoute
  SurveyTopoExportRoute: typeof SurveyTopoExportRoute
}
const SurveyTopoRouteChildren: SurveyTopoRouteChildren = {
  SurveyTopoImportRoute, SurveyTopoContourRoute, SurveyTopoExportRoute,
}
const SurveyTopoRouteWithChildren = SurveyTopoRoute._addFileChildren(SurveyTopoRouteChildren)

interface SurveyGprRouteChildren {
  SurveyGprRadargramRoute: typeof SurveyGprRadargramRoute
}
const SurveyGprRouteChildren: SurveyGprRouteChildren = { SurveyGprRadargramRoute }
const SurveyGprRouteWithChildren = SurveyGprRoute._addFileChildren(SurveyGprRouteChildren)

interface SurveyErtRouteChildren {
  SurveyErtHeatmapRoute: typeof SurveyErtHeatmapRoute
  SurveyErtAnomalyRoute: typeof SurveyErtAnomalyRoute
}
const SurveyErtRouteChildren: SurveyErtRouteChildren = {
  SurveyErtHeatmapRoute, SurveyErtAnomalyRoute,
}
const SurveyErtRouteWithChildren = SurveyErtRoute._addFileChildren(SurveyErtRouteChildren)

interface SurveyRouteChildren {
  SurveyTopoRoute: typeof SurveyTopoRouteWithChildren
  SurveyGprRoute: typeof SurveyGprRouteWithChildren
  SurveyErtRoute: typeof SurveyErtRouteWithChildren
}
const SurveyRouteChildren: SurveyRouteChildren = {
  SurveyTopoRoute: SurveyTopoRouteWithChildren,
  SurveyGprRoute: SurveyGprRouteWithChildren,
  SurveyErtRoute: SurveyErtRouteWithChildren,
}
const SurveyRouteWithChildren = SurveyRoute._addFileChildren(SurveyRouteChildren)

interface DetectorHistoryRouteChildren {
  DetectorHistoryScanIdRoute: typeof DetectorHistoryScanIdRoute
}
const DetectorHistoryRouteChildren: DetectorHistoryRouteChildren = { DetectorHistoryScanIdRoute }
const DetectorHistoryRouteWithChildren = DetectorHistoryRoute._addFileChildren(DetectorHistoryRouteChildren)

interface DetectorRouteChildren {
  DetectorResultsRoute: typeof DetectorResultsRoute
  DetectorHistoryRoute: typeof DetectorHistoryRouteWithChildren
}
const DetectorRouteChildren: DetectorRouteChildren = {
  DetectorResultsRoute,
  DetectorHistoryRoute: DetectorHistoryRouteWithChildren,
}
const DetectorRouteWithChildren = DetectorRoute._addFileChildren(DetectorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute,
  ForgotPasswordRoute,
  HomeRoute,
  LoginRoute,
  OnboardingRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  RegisterRoute,
  SurveyRoute: SurveyRouteWithChildren,
  DetectorRoute: DetectorRouteWithChildren,
}

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
